### ISSUE TITLE
Test suite KO : Invalid signature file digest for Manifest main attributes

### ISSUE THREAD

**Issue by jmvanel** [w3c/ldp-testsuite#232]
The latest commit https://github.com/w3c/ldp-testsuite/commit/6b8da35c66f6d5f280a7507887444812cee4ae8b seems harmful :( 

```
java -jar target/ldp-testsuite-0.2.0-SNAPSHOT-shaded.jar      --server http://localhost:9000/ldp/test-suite --basic      --httpLogging 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:314)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:316)
	at java.util.jar.JarVerifier.update(JarVerifier.java:228)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
	at java.util.jar.JarFile.getInputStream(JarFile.java:450)
	at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:977)
	at sun.misc.Resource.cachedInputStream(Resource.java:77)
	at sun.misc.Resource.getByteBuffer(Resource.java:160)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```
Context:
```shell
java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
jmv@jmv-SMBIOSation:~/src/ldp-testsuite$ uname -a
Linux jmv-SMBIOSation 4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by michielbdejong** [comment]
Ha, I was a bit confused that you reported this on 29 March, 2 days into the future, but then saw the 2018 year on it. :)

Thanks for clarifying the commit that broke this, `git checkout 6b8da35~` and then running `mvn package` again indeed got rid of this error!

**Comment by rimmartin** [comment]
Hi,

just tried the latest HEAD and the issue is still there

**Comment by acoburn** [comment]
@rimmartin you might have more luck by simply disabling the GPG plugin from the command line (for newer versions of Java, skipping the javadoc stage is also necessary):

```sh
$ mvn install -Dgpg.skip -Dmaven.javadoc.skip
```

**Comment by rimmartin** [comment]
Hi @acoburn 

I found the https://travis-ci.com/trellis-ldp/ldp-testsuite showing it skipped as you note.  then next hit this #232 issue.

I could use git checkout 6b8da35~ as suggested above but am thinking about finding the actual code changes and make a pull request going the other way.  However I get further and further away from projects I should be maintaining:-)

**Comment by acoburn** [comment]
@rimmartin please see [this comment](https://github.com/w3c/ldp-testsuite/issues/229#issuecomment-250448306), explaining that this codebase is stable/unmaintained. You may find that forking this project is the most expedient way to add features and address bugs. The CI link you refer to above is from my own fork of this project at https://github.com/trellis-ldp/ldp-testsuite

**Comment by michielbdejong** [comment]
> I could use `git checkout 6b8da35~`

@rimmartin just to confirm what Aaron said, I wouldn't do that, I would use https://github.com/trellis-ldp/ldp-testsuite instead. From my research, that's currently the most usable version of this test suite.
